@value @forge_core @tools @workspace
Feature: Workspace file persistence and boundaries
  As a developer using forgeCodeAgent
  I want the runtime to persist files safely in the workspace
  So that my automations can materialize code changes directly in the project

  Background:
    Given a clean working directory configured for the project

  @happy_path @files
  @ci-int
  Scenario: Persist generated files in the workspace
    Given there is a CodeAgent configured with an empty working directory
    When the developer executes a prompt that generates a code module
    Then the runtime creates the corresponding files inside the working directory
    And the file contents reflect the code generated by the engine
    And no files are written outside the configured workspace

  @security @workspace_boundaries
  @ci-int @ci-security
  Scenario: Prevent file writes outside the workspace
    Given a CodeAgent configured with working directory "/project"
    And the engine attempts to generate a file with path "../outside/file.py"
    When the runtime processes the file write request
    Then the runtime rejects the write operation
    And the developer receives an error indicating forbidden path traversal
